### PR TITLE
Updates to the Legion implementation of Stencil

### PR DESCRIPTION
**Pull request by magnatelee**

### CODE REVIEW

**Comment by jeffhammond** [comment]
Before you resubmit this, please clean up the pull request by removing whatever changes to made to serial PIC and the timing changes to MPI1 and MPIOPENMP stencil.  I don't see any reason for the former and the latter is a separate issue that doesn't belong in this pull request.

On the subject of stencil timings, there should not be any need to do the min/max reduction over timings.  The issue is that there isn't a barrier after the end of the iterations before the timer is stopped.  If a barrier is added there, then the timings will be consistent.  This is how the other PRKs are timed.  Perhaps @rfvander has another opinion...

**Comment by rfvander** [comment]
There are two equivalent ways to get consistent timings. Presuming that the timer is started upon exiting a barrier after the first warmup iteration, the end time can be obtained either by placing a barrier after the last iteration and recording the end time for any worker/rank/thread, or by recording the end times for all workers, subtracting the start time, and obtaining the maximum over all resulting wall times (the method used in many of the other PRKs).

**Comment by jeffhammond** [comment]
We use the barrier method of timing most of the time, and I prefer to be consistent.

Given that multiple PGAS models have barrier but not reductions, it allows us to be more consistent across programming environments if we use the barrier method.

**Comment by rfvander** [comment]
Then let’s make sure we use the barrier variety throughout. I will take that as an action item.

**Comment by magnatelee** [comment]
I cleaned things up and submitted another pull request against the upstream repo. Since nothing related to Legion has been pushed to that repo, I had to cherry-pick only Legion-related commits on the current master. It's already rebased to the master branch, so there wouldn't be too much hassle to merge it back to the trunk.

Note that the current code is still doing min reduction on the starting timestamps. This is necessary under the deferred execution model Legion programming system is based on. When a task launches a sub-task in Legion, that task isn't started right away but pushed to the analysis pipeline. So, it's only possible to get the starting timestamp once the task started its execution.

I'll close this thread as soon as the other one is merged.

**Comment by jeffhammond** [comment]
https://github.com/ParRes/Kernels/pull/95 has been merged.

**Pull request closed without merging**
